name: simple-composite-workflow
on: [push]

jobs:
  hellow_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: checkout@v2 use step
        id: checkout-step
        uses: actions/checkout@v2
      - name: action-simple-composite@v1 use step
        id: action-simple-composite-step
        uses: EunPyoLee/action-simple-composite@v1
        with:
          who-to-greet: '${{github.actor}}'
      - name: print random number step
        id: print-random-number-step
        run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash